# Generated by Django 4.0.4 on 2022-05-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('address', models.TextField()),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_name', models.CharField(max_length=200)),
                ('contribution_details', models.TextField()),
                ('contribution_targeted_amount', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'ordering': ['contribution_name', 'contribution_targeted_amount'],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=19)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribution.contribution')),
                ('contributor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribution.churchmember')),
            ],
            options={
                'ordering': ['contributor_name', 'amount_paid'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('contributor_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='contribution.contributor')),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
    ]
