# Generated by Django 4.0.4 on 2022-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='gender',
            field=models.CharField(max_length=2),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
